// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

/**
 * Token usage attributed to one exact model inside an immutable lifecycle snapshot.
 */
export type ModelTokenUsageSnapshot = { model: string | null, usage: TokenUsageBreakdown | null, incomplete: boolean, };
