// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageSnapshot } from "./TokenUsageSnapshot";

/**
 * Root, agent, and combined per-model totals frozen at root-turn completion.
 */
export type RootTurnTokenUsageSnapshot = { turn: TokenUsageSnapshot, agents: TokenUsageSnapshot, total: TokenUsageSnapshot, agentCount: number, runningAgentCount: number, };
