// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTokenUsageSnapshot } from "./ModelTokenUsageSnapshot";

/**
 * Per-model token totals captured at one display or lifecycle boundary.
 */
export type TokenUsageSnapshot = { models: Array<ModelTokenUsageSnapshot>, };
